---
# tasks file for pxeboot on Ubuntu

# https://help.ubuntu.com/community/Installation/Netboot
# copy ubuntu netboot tar from http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/installer-amd64/current/images/hwe-netboot/netboot.tar.gz
#
# focal changed install process
# https://discourse.ubuntu.com/t/netbooting-the-live-server-installer/14510

- name: UBUNTU netboot.tar.gz FILE (~2 MINUTES)
  get_url:
    url: "{{ vars[ansible_distribution_release + '_netboot'] }}"
    dest: /tmp/netboot.tar.gz
    checksum: "{{ vars[ansible_distribution_release + '_checksum'] }}"
  register: url
- debug: var=url.url

- name: UBUNTU unpack netboot.tar.gz file
  unarchive:
    src: /tmp/netboot.tar.gz
    dest: /var/lib/tftpboot/
    creates: /var/lib/tftpboot/pxelinux.0
    remote_src: yes
  register: tar
#- debug: var=tar

# 5/14/20 no netboot.tar.gz for focal yet
# https://community.spiceworks.com/topic/2269656-fog-looks-like-netboot-not-up-yet-for-focal-fossa
# https://bugs.launchpad.net/ubuntu-cdimage/+bug/1866530